/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'inventory-brands': RouteRecordInfo<'inventory-brands', '/inventory/brands', Record<never, never>, Record<never, never>>,
    'inventory-category': RouteRecordInfo<'inventory-category', '/inventory/category', Record<never, never>, Record<never, never>>,
    'inventory-movements-tab': RouteRecordInfo<'inventory-movements-tab', '/inventory/movements/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'inventory-presentation': RouteRecordInfo<'inventory-presentation', '/inventory/presentation', Record<never, never>, Record<never, never>>,
    'inventory-product': RouteRecordInfo<'inventory-product', '/inventory/product', Record<never, never>, Record<never, never>>,
    'inventory-product-edit-producto': RouteRecordInfo<'inventory-product-edit-producto', '/inventory/product/EditProducto', Record<never, never>, Record<never, never>>,
    'inventory-product-register-producto': RouteRecordInfo<'inventory-product-register-producto', '/inventory/product/RegisterProducto', Record<never, never>, Record<never, never>>,
    'inventory-sub-category': RouteRecordInfo<'inventory-sub-category', '/inventory/sub-category', Record<never, never>, Record<never, never>>,
    'inventory-warehouse': RouteRecordInfo<'inventory-warehouse', '/inventory/warehouse', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
  }
}
